
@HOST_NAME = https://localhost:5001

### GetAllBooks
GET {{HOST_NAME}}/api/books/  HTTP/1.1


### GetBookById
GET {{HOST_NAME}}/api/books/5/  HTTP/1.1

### AddBook
POST {{HOST_NAME}}/api/books/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer XXX

{
    "Name": "Ultimate ASP.NET Core Web API",
    "Description": "Ultimate ASP.NET Core Web API"
}

### UpdateBook
PUT {{HOST_NAME}}/api/books/5/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer XXX

{
    "name": "Software Development and Professional Practice",
    "description": "Software development and professional practice"
}

### UpdateBookByPatch
PATCH {{HOST_NAME}}/api/books/5/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer XXX

[
    {
        "op": "replace",
        "path": "Description",
        "value": "Software development and professional practice"
    }
]

### DeleteBook
DELETE {{HOST_NAME}}/api/books/7/  HTTP/1.1
Authorization: Bearer XXX